/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useRef, useState } from 'react'

import styles from '../styles/Home.module.css'

export default function Game() {

    // SCROLL //

    const [header, setHeader] = useState(false);

    const changeHeader = () => {
        if (window.scrollY >= 80) {
            setHeader(true);
        } else {
            setHeader(false);
        }
    }

    useEffect(() => {
        window.addEventListener("scroll", changeHeader);
    }, []);

    //RELOJ//

    const [TimerDays, setTimerDays] = useState('00');
    const [TimerHours, setTimerHours] = useState('00');
    const [TimerMinutes, setTimerMinutes] = useState('00');

    let interval = useRef();

    const starTimer = () => {
        const countDownDate = new Date('Nov 20 2022 13:00:00').getTime();

        interval = setInterval(() => {
            const now = new Date().getTime();
            const distance = countDownDate - now;

            const days = Math.floor(distance / (1000 * 60 * 60 * 24));
            const hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
            const minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));

            if (distance <= 0) {
                clearInterval(interval.current);
            } else {
                setTimerDays(days);
                setTimerHours(hours);
                setTimerMinutes(minutes);
            };
        }, 1000);
    };

    useEffect(() => {
        starTimer();
        return () => {
            clearInterval(interval)
        }
    });

    return (
        <div className={styles.container}>
            <Head>
                <meta charset="UTF-8" />
                <meta http-equiv="X-UA-Compatible" content="IE=edge" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <title>Game | World Proyect</title>
                <meta name="description" content="Generated by World Proyect" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section className={styles.body}>
                <header className={header ? styles.header2 : styles.header}>
                    <div>
                        <div className={styles.logo1}></div>
                        <h4>World Proyect</h4>
                    </div>
                    <div>
                        <a href="#info">Infromacion</a>
                        <Image src="/img/rombo.jpg" alt="Rombo" width={8} height={8} />
                        <a href="#groups">Fase de Grupos</a>
                        <Image src="/img/rombo.jpg" alt="Rombo" width={8} height={8} />
                        <a href="#people">Personas</a>
                    </div>
                    <a href="#"><button>Cerrar Sesion</button></a>
                </header>

                <section className={styles.cont}>
                    <div className={styles.video}>
                        <video src="/img/qatar.mp4" loop autoPlay muted></video>
                    </div>
                    <div className={styles.timer2}>
                        <div>
                            <h4>{TimerDays}</h4>
                            <p>Dias</p>
                        </div>
                        <Image src="/img/rombo.jpg" alt="Rombo" width={8} height={8} />
                        <div>
                            <h4>{TimerHours}</h4>
                            <p>Horas</p>
                        </div>
                        <Image src="/img/rombo.jpg" alt="Rombo" width={8} height={8} />
                        <div>
                            <h4>{TimerMinutes}</h4>
                            <p>Min</p>
                        </div>
                    </div>
                    <div className={styles.redirect}>
                        <h1>World Proyect</h1>
                    </div>
                </section>

                <form className={styles.game} action="">
                    <h2>COMIENZA EL JUEGO</h2>

                    {/* GRUPO A */}
                    <div className={styles.game_groups}>
                        <h4>Grupo A</h4>
                        <div>
                            <img src="/img/selections/QAT.jpg" alt="" />
                            <p>A1 - Qatar</p>
                            <h4>0</h4>
                        </div>
                        <div>
                            <img src="/img/selections/ECU.jpg" alt="" />
                            <p>A2 - Ecuador</p>
                            <h4>0</h4>
                        </div>
                        <div>
                            <img src="/img/selections/SEN.jpg" alt="" />
                            <p>A3 - Senegal</p>
                            <h4>0</h4>
                        </div>
                        <div>
                            <img src="/img/selections/NED.jpg" alt="" />
                            <p>A4 - Netherlands</p>
                            <h4>0</h4>
                        </div>
                    </div>
                    <div className={styles.result}>
                        <div className={styles.result_cont}>
                            <p>Fecha 1</p>
                            <div className={styles.form}>
                                <img src="/img/selections/QAT.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/ECU.jpg" alt="" />
                            </div>

                            <div className={styles.form}>
                                <img src="/img/selections/SEN.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/NED.jpg" alt="" />
                            </div>
                        </div>

                        <div className={styles.result_cont}>
                            <p>Fecha 2</p>
                            <div className={styles.form}>
                                <img src="/img/selections/QAT.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/SEN.jpg" alt="" />
                            </div>

                            <div className={styles.form}>
                                <img src="/img/selections/NED.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/ECU.jpg" alt="" />
                            </div>
                        </div>

                        <div className={styles.result_cont}>
                            <p>Fecha 3</p>
                            <div className={styles.form}>
                                <img src="/img/selections/NED.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/QAT.jpg" alt="" />
                            </div>

                            <div className={styles.form}>
                                <img src="/img/selections/ECU.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/SEN.jpg" alt="" />
                            </div>
                        </div>
                    </div>
                    {/* GRUPO B */}
                    <div className={styles.game_groups}>
                        <h4>Grupo B</h4>
                        <div>
                            <img src="/img/selections/ENG.jpg" alt="" />
                            <p>B1 - England</p>
                            <h4>0</h4>
                        </div>
                        <div>
                            <img src="/img/selections/IRN.jpg" alt="" />
                            <p>B2 - IR Iran</p>
                            <h4>0</h4>
                        </div>
                        <div>
                            <img src="/img/selections/USA.jpg" alt="" />
                            <p>B3 - USA</p>
                            <h4>0</h4>
                        </div>
                        <div>
                            <img src="/img/selections/WAL.jpg" alt="" />
                            <p>B4 - Wales</p>
                            <h4>0</h4>
                        </div>
                    </div>

                    <div className={styles.result}>
                        <div className={styles.result_cont}>
                            <p>Fecha 1</p>
                            <div className={styles.form}>
                                <img src="/img/selections/ENG.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/IRN.jpg" alt="" />
                            </div>

                            <div className={styles.form}>
                                <img src="/img/selections/USA.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/WAL.jpg" alt="" />
                            </div>
                        </div>

                        <div className={styles.result_cont}>
                            <p>Fecha 2</p>
                            <div className={styles.form}>
                                <img src="/img/selections/WAL.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/IRN.jpg" alt="" />
                            </div>

                            <div className={styles.form}>
                                <img src="/img/selections/ENG.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/USA.jpg" alt="" />
                            </div>
                        </div>

                        <div className={styles.result_cont}>
                            <p>Fecha 3</p>
                            <div className={styles.form}>
                                <img src="/img/selections/WAL.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/ENG.jpg" alt="" />
                            </div>

                            <div className={styles.form}>
                                <img src="/img/selections/IRN.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/USA.jpg" alt="" />
                            </div>
                        </div>
                    </div>
                    {/* GRUPO C */}
                    <div className={styles.game_groups}>
                        <h4>Grupo C</h4>
                        <div>
                            <img src="/img/selections/ARG.jpg" alt="" />
                            <p>C1 - Argentina</p>
                            <h4>0</h4>
                        </div>
                        <div>
                            <img src="/img/selections/KSA.jpg" alt="" />
                            <p>C2 - Saudi Arabia</p>
                            <h4>0</h4>
                        </div>
                        <div>
                            <img src="/img/selections/MEX.jpg" alt="" />
                            <p>C3 - Mexico</p>
                            <h4>0</h4>
                        </div>
                        <div>
                            <img src="/img/selections/POL.jpg" alt="" />
                            <p>C4 - Poland</p>
                            <h4>0</h4>
                        </div>
                    </div>

                    <div className={styles.result}>
                        <div className={styles.result_cont}>
                            <p>Fecha 1</p>
                            <div className={styles.form}>
                                <img src="/img/selections/ARG.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/KSA.jpg" alt="" />
                            </div>

                            <div className={styles.form}>
                                <img src="/img/selections/MEX.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/POL.jpg" alt="" />
                            </div>
                        </div>

                        <div className={styles.result_cont}>
                            <p>Fecha 2</p>
                            <div className={styles.form}>
                                <img src="/img/selections/POL.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/KSA.jpg" alt="" />
                            </div>

                            <div className={styles.form}>
                                <img src="/img/selections/ARG.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/MEX.jpg" alt="" />
                            </div>
                        </div>

                        <div className={styles.result_cont}>
                            <p>Fecha 3</p>
                            <div className={styles.form}>
                                <img src="/img/selections/POL.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/ARG.jpg" alt="" />
                            </div>

                            <div className={styles.form}>
                                <img src="/img/selections/KSA.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/MEX.jpg" alt="" />
                            </div>
                        </div>
                    </div>
                    {/* GRUPO D */}
                    <div className={styles.game_groups}>
                        <h4>Grupo D</h4>
                        <div>
                            <img src="/img/selections/FRA.jpg" alt="" />
                            <p>D1 - France</p>
                            <h4>0</h4>
                        </div>
                        <div>
                            <img src="/img/selections/AUS.jpg" alt="" />
                            <p>D2 - Denmark</p>
                            <h4>0</h4>
                        </div>
                        <div>
                            <img src="/img/selections/DEN.jpg" alt="" />
                            <p>D3 - Tunisia</p>
                            <h4>0</h4>
                        </div>
                        <div>
                            <img src="/img/selections/TUN.jpg" alt="" />
                            <p>D4 - Australia</p>
                            <h4>0</h4>
                        </div>
                    </div>

                    <div className={styles.result}>
                        <div className={styles.result_cont}>
                            <p>Fecha 1</p>
                            <div className={styles.form}>
                                <img src="/img/selections/DEN.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/TUN.jpg" alt="" />
                            </div>

                            <div className={styles.form}>
                                <img src="/img/selections/FRA.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/AUS.jpg" alt="" />
                            </div>
                        </div>

                        <div className={styles.result_cont}>
                            <p>Fecha 2</p>
                            <div className={styles.form}>
                                <img src="/img/selections/TUN.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/AUS.jpg" alt="" />
                            </div>

                            <div className={styles.form}>
                                <img src="/img/selections/FRA.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/DEN.jpg" alt="" />
                            </div>
                        </div>

                        <div className={styles.result_cont}>
                            <p>Fecha 3</p>
                            <div className={styles.form}>
                                <img src="/img/selections/TUN.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/FRA.jpg" alt="" />
                            </div>

                            <div className={styles.form}>
                                <img src="/img/selections/AUS.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/DEN.jpg" alt="" />
                            </div>
                        </div>
                    </div>

                    {/* GRUPO E */}
                    <div className={styles.game_groups}>
                        <h4>Grupo E</h4>
                        <div>
                            <img src="/img/selections/ESP.jpg" alt="" />
                            <p>E1 - Spain</p>
                            <h4>0</h4>
                        </div>
                        <div>
                            <img src="/img/selections/GER.jpg" alt="" />
                            <p>E2 - Germany</p>
                            <h4>0</h4>
                        </div>
                        <div>
                            <img src="/img/selections/JPN.jpg" alt="" />
                            <p>E3 - Japan</p>
                            <h4>0</h4>
                        </div>
                        <div>
                            <img src="/img/selections/CRC.jpg" alt="" />
                            <p>E4 - Costa Rica</p>
                            <h4>0</h4>
                        </div>
                    </div>

                    <div className={styles.result}>
                        <div className={styles.result_cont}>
                            <p>Fecha 1</p>
                            <div className={styles.form}>
                                <img src="/img/selections/GER.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/JPN.jpg" alt="" />
                            </div>

                            <div className={styles.form}>
                                <img src="/img/selections/ESP.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/CRC.jpg" alt="" />
                            </div>
                        </div>

                        <div className={styles.result_cont}>
                            <p>Fecha 2</p>
                            <div className={styles.form}>
                                <img src="/img/selections/JPN.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/CRC.jpg" alt="" />
                            </div>

                            <div className={styles.form}>
                                <img src="/img/selections/ESP.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/GER.jpg" alt="" />
                            </div>
                        </div>

                        <div className={styles.result_cont}>
                            <p>Fecha 3</p>
                            <div className={styles.form}>
                                <img src="/img/selections/JPN.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/ESP.jpg" alt="" />
                            </div>

                            <div className={styles.form}>
                                <img src="/img/selections/CRC.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/GER.jpg" alt="" />
                            </div>
                        </div>
                    </div>

                    {/* GRUPO F */}
                    <div className={styles.game_groups}>
                        <h4>Grupo F</h4>
                        <div>
                            <img src="/img/selections/BEL.jpg" alt="" />
                            <p>F1 - Belgium</p>
                            <h4>0</h4>
                        </div>
                        <div>
                            <img src="/img/selections/CAN.jpg" alt="" />
                            <p>F2 - Canada</p>
                            <h4>0</h4>
                        </div>
                        <div>
                            <img src="/img/selections/MAR.jpg" alt="" />
                            <p>F3 - Morocco</p>
                            <h4>0</h4>
                        </div>
                        <div>
                            <img src="/img/selections/CRO.jpg" alt="" />
                            <p>F4 - Croatia</p>
                            <h4>0</h4>
                        </div>
                    </div>

                    <div className={styles.result}>
                        <div className={styles.result_cont}>
                            <p>Fecha 1</p>
                            <div className={styles.form}>
                                <img src="/img/selections/MAR.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/CRO.jpg" alt="" />
                            </div>

                            <div className={styles.form}>
                                <img src="/img/selections/BEL.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/CAN.jpg" alt="" />
                            </div>
                        </div>

                        <div className={styles.result_cont}>
                            <p>Fecha 2</p>
                            <div className={styles.form}>
                                <img src="/img/selections/BEL.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/MAR.jpg" alt="" />
                            </div>

                            <div className={styles.form}>
                                <img src="/img/selections/CRO.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/CAN.jpg" alt="" />
                            </div>
                        </div>

                        <div className={styles.result_cont}>
                            <p>Fecha 3</p>
                            <div className={styles.form}>
                                <img src="/img/selections/CRO.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/BEL.jpg" alt="" />
                            </div>

                            <div className={styles.form}>
                                <img src="/img/selections/CAN.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/MAR.jpg" alt="" />
                            </div>
                        </div>
                    </div>

                    {/* GRUPO G */}
                    <div className={styles.game_groups}>
                        <h4>Grupo G</h4>
                        <div>
                            <img src="/img/selections/BRA.jpg" alt="" />
                            <p>G1 - Brazil</p>
                            <h4>0</h4>
                        </div>
                        <div>
                            <img src="/img/selections/SRB.jpg" alt="" />
                            <p>G2 - Serbia</p>
                            <h4>0</h4>
                        </div>
                        <div>
                            <img src="/img/selections/SUI.jpg" alt="" />
                            <p>G3 - Switzerland</p>
                            <h4>0</h4>
                        </div>
                        <div>
                            <img src="/img/selections/CMR.jpg" alt="" />
                            <p>G4 - Cameroon</p>
                            <h4>0</h4>
                        </div>
                    </div>

                    <div className={styles.result}>
                        <div className={styles.result_cont}>
                            <p>Fecha 1</p>
                            <div className={styles.form}>
                                <img src="/img/selections/SUI.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/CMR.jpg" alt="" />
                            </div>

                            <div className={styles.form}>
                                <img src="/img/selections/BRA.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/SRB.jpg" alt="" />
                            </div>
                        </div>

                        <div className={styles.result_cont}>
                            <p>Fecha 2</p>
                            <div className={styles.form}>
                                <img src="/img/selections/CMR.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/SRB.jpg" alt="" />
                            </div>

                            <div className={styles.form}>
                                <img src="/img/selections/BRA.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/SUI.jpg" alt="" />
                            </div>
                        </div>

                        <div className={styles.result_cont}>
                            <p>Fecha 3</p>
                            <div className={styles.form}>
                                <img src="/img/selections/CMR.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/BRA.jpg" alt="" />
                            </div>

                            <div className={styles.form}>
                                <img src="/img/selections/SRB.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/SUI.jpg" alt="" />
                            </div>
                        </div>
                    </div>

                    {/* GRUPO H */}
                    <div className={styles.game_groups}>
                        <h4>Grupo H</h4>
                        <div>
                            <img src="/img/selections/POR.jpg" alt="" />
                            <p>H1 - Portugal</p>
                            <h4>0</h4>
                        </div>
                        <div>
                            <img src="/img/selections/GHA.jpg" alt="" />
                            <p>H2 - Ghana</p>
                            <h4>0</h4>
                        </div>
                        <div>
                            <img src="/img/selections/URU.jpg" alt="" />
                            <p>H3 - Uruguay</p>
                            <h4>0</h4>
                        </div>
                        <div>
                            <img src="/img/selections/KOR.jpg" alt="" />
                            <p>H4 - Korea Republic</p>
                            <h4>0</h4>
                        </div>
                    </div>

                    <div className={styles.result}>
                        <div className={styles.result_cont}>
                            <p>Fecha 1</p>
                            <div className={styles.form}>
                                <img src="/img/selections/URU.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/KOR.jpg" alt="" />
                            </div>

                            <div className={styles.form}>
                                <img src="/img/selections/POR.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/GHA.jpg" alt="" />
                            </div>
                        </div>

                        <div className={styles.result_cont}>
                            <p>Fecha 2</p>
                            <div className={styles.form}>
                                <img src="/img/selections/KOR.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/GHA.jpg" alt="" />
                            </div>

                            <div className={styles.form}>
                                <img src="/img/selections/POR.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/URU.jpg" alt="" />
                            </div>
                        </div>

                        <div className={styles.result_cont}>
                            <p>Fecha 3</p>
                            <div className={styles.form}>
                                <img src="/img/selections/KOR.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/POR.jpg" alt="" />
                            </div>

                            <div className={styles.form}>
                                <img src="/img/selections/GHA.jpg" alt="" />
                                <input type="number" min="0" max="9" required />
                                <p>-</p>
                                <input type="number" min="0" max="9" required />
                                <img src="/img/selections/URU.jpg" alt="" />
                            </div>
                        </div>
                    </div>
                    {/* <a href="#register"><button className={styles.button}>Enviar</button></a> */}
                </form>

            </section>

        </div>
    );
};