/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useRef, useState } from 'react'
import Timer from '../components/timer2';
import Nav from '../components/nav';
import { MongoClient } from 'mongodb';

import styles from '../styles/Home.module.css'

export async function getStaticProps() {
    const client = await MongoClient.connect(process.env.MONGODB_URI);
    const db = client.db();

    const accountsCollection = db.collection('accounts');

    const accounts = await accountsCollection.countDocuments();
    client.close();

    return {
        props: {
            accounts: accounts,
        },
        revalidate: 1,
    };
}

export default function Home({accounts}) {
    return (
        <div className={styles.container}>
            <Head>
                <meta charset="UTF-8" />
                <meta http-equiv="X-UA-Compatible" content="IE=edge" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <title>Home | Mundialito</title>
                <meta name="description" content="Generated by Mundialito" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Nav />

            <section className={styles.cont}>
                <div className={styles.video}>
                    <video src="/img/qatar.mp4" loop autoPlay muted></video>
                </div>
                <Timer />
                <div className={styles.redirect}>
                    <h1>Mundialito</h1>
                    <a href="#info"><button className={styles.button}>Mas información</button></a>
                </div>
            </section>

            <section className={styles.informative} id="info">
                <div>
                    <h2>Informacion sobre la Pagina</h2>
                    <p>Esta pagina es proyecto de un arduo trabajo de dos compañeros y amigos, de la escuela tecnica n°5 de Mar del Plata, con el objetivo de informar sobre el mundial a las diversas personas, no se me ocurrio mas</p>
                </div>
                <div>
                    <p>world Cup</p>
                </div>
            </section>

            <section className={styles.groups} id="groups">
                <div className={styles.groups_info}>
                    <h2>Informacion Sobre Equipos</h2>
                    <p>Al tocar en alguna soleccion vas a poder ver la informacion de la misma, esto contara con el cuerpo tecnico, informacion sobre la seleccion, los 26 jugadores seleccionados y algunos datos especiales, en la cual vas a poder seleccionar a tu jugador favorito para poder ver sus estadisticas</p>
                </div>
                <div className={styles.game} action="">

                    {/* GRUPO A */}
                    <div className={styles.game_groups}>
                        <h4>Grupo A</h4>
                        <div>
                            <img src="/img/selections/QAT.jpg" alt="" />
                            <p>Qatar</p>
                        </div>
                        <div>
                            <img src="/img/selections/ECU.jpg" alt="" />
                            <p>Ecuador</p>
                        </div>
                        <div>
                            <img src="/img/selections/SEN.jpg" alt="" />
                            <p>Senegal</p>
                        </div>
                        <div>
                            <img src="/img/selections/NED.jpg" alt="" />
                            <p>Netherlands</p>
                        </div>
                    </div>
                    {/* GRUPO B */}
                    <div className={styles.game_groups}>
                        <h4>Grupo B</h4>
                        <div>
                            <img src="/img/selections/ENG.jpg" alt="" />
                            <p>England</p>
                        </div>
                        <div>
                            <img src="/img/selections/IRN.jpg" alt="" />
                            <p>IR Iran</p>
                        </div>
                        <div>
                            <img src="/img/selections/USA.jpg" alt="" />
                            <p>USA</p>
                        </div>
                        <div>
                            <img src="/img/selections/WAL.jpg" alt="" />
                            <p>Wales</p>
                        </div>
                    </div>
                    {/* GRUPO C */}
                    <div className={styles.game_groups}>
                        <h4>Grupo C</h4>
                        <div>
                            <img src="/img/selections/ARG.jpg" alt="" />
                            <p>Argentina</p>
                        </div>
                        <div>
                            <img src="/img/selections/KSA.jpg" alt="" />
                            <p>Saudi Arabia</p>
                        </div>
                        <div>
                            <img src="/img/selections/MEX.jpg" alt="" />
                            <p>Mexico</p>
                        </div>
                        <div>
                            <img src="/img/selections/POL.jpg" alt="" />
                            <p>Poland</p>
                        </div>
                    </div>
                    {/* GRUPO D */}
                    <div className={styles.game_groups}>
                        <h4>Grupo D</h4>
                        <div>
                            <img src="/img/selections/FRA.jpg" alt="" />
                            <p>France</p>
                        </div>
                        <div>
                            <img src="/img/selections/AUS.jpg" alt="" />
                            <p>Denmark</p>
                        </div>
                        <div>
                            <img src="/img/selections/DEN.jpg" alt="" />
                            <p>Tunisia</p>
                        </div>
                        <div>
                            <img src="/img/selections/TUN.jpg" alt="" />
                            <p>Australia</p>
                        </div>
                    </div>
                    {/* GRUPO E */}
                    <div className={styles.game_groups}>
                        <h4>Grupo E</h4>
                        <div>
                            <img src="/img/selections/ESP.jpg" alt="" />
                            <p>Spain</p>
                        </div>
                        <div>
                            <img src="/img/selections/GER.jpg" alt="" />
                            <p>Germany</p>
                        </div>
                        <div>
                            <img src="/img/selections/JPN.jpg" alt="" />
                            <p>Japan</p>
                        </div>
                        <div>
                            <img src="/img/selections/CRC.jpg" alt="" />
                            <p>Costa Rica</p>
                        </div>
                    </div>
                    {/* GRUPO F */}
                    <div className={styles.game_groups}>
                        <h4>Grupo F</h4>
                        <div>
                            <img src="/img/selections/BEL.jpg" alt="" />
                            <p>Belgium</p>
                        </div>
                        <div>
                            <img src="/img/selections/CAN.jpg" alt="" />
                            <p>Canada</p>
                        </div>
                        <div>
                            <img src="/img/selections/MAR.jpg" alt="" />
                            <p>Morocco</p>
                        </div>
                        <div>
                            <img src="/img/selections/CRO.jpg" alt="" />
                            <p>Croatia</p>
                        </div>
                    </div>
                    {/* GRUPO G */}
                    <div className={styles.game_groups}>
                        <h4>Grupo G</h4>
                        <div>
                            <img src="/img/selections/BRA.jpg" alt="" />
                            <p>Brazil</p>
                        </div>
                        <div>
                            <img src="/img/selections/SRB.jpg" alt="" />
                            <p>Serbia</p>
                        </div>
                        <div>
                            <img src="/img/selections/SUI.jpg" alt="" />
                            <p>Switzerland</p>
                        </div>
                        <div>
                            <img src="/img/selections/CMR.jpg" alt="" />
                            <p>Cameroon</p>
                        </div>
                    </div>
                    {/* GRUPO H */}
                    <div className={styles.game_groups}>
                        <h4>Grupo H</h4>
                        <div>
                            <img src="/img/selections/POR.jpg" alt="" />
                            <p>Portugal</p>
                        </div>
                        <div>
                            <img src="/img/selections/GHA.jpg" alt="" />
                            <p>Ghana</p>
                        </div>
                        <div>
                            <img src="/img/selections/URU.jpg" alt="" />
                            <p>Uruguay</p>
                        </div>
                        <div>
                            <img src="/img/selections/KOR.jpg" alt="" />
                            <p>South Korea</p>
                        </div>
                    </div>
                    </div>
                </section>

                <section className={styles.people} id="people">
                    <div>
                        <Image src="/img/rombo.jpg" alt="Rombo" width={16} height={16} />
                        <h2>Personas participando</h2>
                        <p>{accounts}</p>
                    </div>
                    <img src="/img/marado.jpg" alt="maradona" />
                </section>
        </div>
    )
}