/* eslint-disable @next/next/no-html-link-for-pages */
/* eslint-disable @next/next/no-img-element */
import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useRef, useState } from 'react'
import styles from '../styles/Home.module.css'


export default function Home() {

  const [TimerDays, setTimerDays] = useState('00');
  const [TimerHours, setTimerHours] = useState('00');
  const [TimerMinutes, setTimerMinutes] = useState('00');

  let interval = useRef();

  const starTimer = () => {
    const countDownDate = new Date('Nov 20 2022 13:00:00').getTime();

    interval = setInterval(() => {
      const now = new Date().getTime();
      const distance = countDownDate - now;

      const days = Math.floor(distance / (1000 * 60 * 60 * 24));
      const hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
      const minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));

      if (distance <= 0) {
        clearInterval(interval.current);
      } else {
        setTimerDays(days);
        setTimerHours(hours);
        setTimerMinutes(minutes);
      };
    }, 1000);
  };

  useEffect(() => {
    starTimer();
    return () => {
      clearInterval(interval)
    }
  });

  return (
    <div className={styles.container}>
      <Head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>World Proyect</title>
        <meta name="description" content="Generated by World Proyect" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <section className={styles.entry}>
        <div className={styles.logo}>
          <Image src="/img/logo.jpg" alt="Mundial Logo" width={120} height={70} />
        </div>
        <div className={styles.messi}></div>
        <h1>World Proyect</h1>
        <a href="/home"><button className={styles.button}>Ingresar</button></a>
        <div className={styles.timer}>
          <div>
            <h4>{TimerDays}</h4>
            <p>Dias</p>
          </div>
          <Image src="/img/rombo.jpg" alt="Rombo" width={8} height={8} />
          <div>
            <h4>{TimerHours}</h4>
            <p>Horas</p>
          </div>
          <Image src="/img/rombo.jpg" alt="Rombo" width={8} height={8} />
          <div>
            <h4>{TimerMinutes}</h4>
            <p>Min</p>
          </div>
        </div>
        <div className={styles.info}>
          <p>En esta y las siguientes paginas vas a poder participar de un juego, el cual va a tener un premio monetario el cual vas a poder tener, si hacertas todos los goles del mundial de futbol Qatar 2022</p>
        </div>
      </section>
    </div>
  )
}
